#!/usr/bin/env zsh
# Usage: git-up
#        git-reup
#
# Like git-pull but show a short and sexy log of changes
# immediately after merging (git-up) or rebasing (git-reup).

set -e

COMMAND="git merge"

test "$(basename $0)" = "git-reup" && COMMAND="git rebase"

git fetch &> /dev/null
changes=`git hist ..origin/master`

eval "$COMMAND origin/master"

if [ -n "$changes" ]; then
  echo "Changelog:"
  echo $changes
fi
