#!/bin/bash
shopt -s globstar
shopt -s extglob

search_for="$1"
search_for_pattern="(\\$|/)$search_for.class"

search_path="$2"
search_path=(${search_path//;/ })

paths=()
jars=()

for sp in "${search_path[@]}"; do
  case $sp in
    *\*.jar)
      globbed_jars=( ${sp}  )
      jars=( "${jars[@]}" "${globbed_jars[@]}" )
      ;;
    *.jar) jars=( "${jars[@]}" $sp ) ;;
    *) paths=( "${paths[@]}" $sp ) ;;
  esac
done

RESULT=()
for p in "${paths[@]}"; do
  esc_path=${p//\//\\/}
  esc_path+="\\/"
  matches=( $(ag -g "$search_for_pattern" "$p" | sed "s/$esc_path//g ; s/\\$/./g ; s/\.class//g ; s/\//\./g") )
  RESULT=( "${RESULT[@]}" "${matches[@]}" )
done

for j in "${jars[@]}"; do
  matches=( $(jar tf "$j" | ag "$search_for_pattern" | sed "s/\\$/./g ; s/\.class//g  ; s/\//\./g")  )
  RESULT=( "${RESULT[@]}" "${matches[@]}" )
done

printf '%s\n' "${RESULT[@]}" | sort -u
