#!/bin/bash

monitor() {
  local pid=$1 i=0

  while ps $pid &>/dev/null; do
    if (( i++ > 5 )); then
      printf "Max checks reached. Sending SIGKILL to %s.\n" "$pid" >&2
      kill -9 $pid; return 1
    fi

    sleep 10
  done

  return 0
}

read -r pid < ~/.offlineimap/pid

if ps $pid &>/dev/null; then
  printf "Process %s already running. Exiting.\n" "$pid" >&2
  exit 1
fi

new_mail_dir="$HOME/Mail/*/*inbox/new/"
old_mail_count="$(find $new_mail_dir -type f | wc -l)"

offlineimap -o -u quiet & monitor $!

new_mail_count="$(find $new_mail_dir -type f | wc -l)"

if [ $new_mail_count -gt 0 ]; then
  export DISPLAY=:0
  export XAUTHORITY=~/.Xauthority
  notify-send -t 20000 -i notification-message-email -a "OfflineIMAP" \
    "You have $new_mail_count unread messages!" "$((new_mail_count-old_mail_count)) of them just received."
fi
